# Generated by Django 6.1 on 2026-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_alumni_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
